All variable changes are now in one place without their traumatic his…
adanter/Prairie pull request #29
Opened 2018-02-08 16:49 UTC by adanter

…tory of having demo merged into them

2018-02-08 19:38 UTC, yinghj commented on Project/Assets/Editor/Twine Importer/TwineJsonParser.cs
> +        Regex invisibleTextRegex = new Regex("(\\[\\[([^\\]]*)\\]\\])|(\\(\\([^)]*\\)\\))");
Commenting the regex. Same as above.

2018-02-08 19:41 UTC, yinghj requested changes

2018-02-08 19:41 UTC, yinghj commented on Project/Assets/Prairie/Framework/Script/Twine/TwineVariables.cs
> +}
Add a newline at the end of file.

2018-02-08 19:41 UTC, yinghj commented on Project/Assets/Editor/Twine Importer/TwineJsonParser.cs
> +        Regex expressionRegex = new Regex("\\(\\([^)]*\\)\\)");
Can you add some comments with examples maybe to indicate what kind of expressions are this is trying to parse? Thank you!

2018-02-08 19:41 UTC, yinghj commented on Project/Assets/Editor/Twine Importer/TwineJsonParser.cs
> +        Regex variableRegex = new Regex("\\$\\w*");
Commenting the regex. Same as above.

2018-02-08 19:41 UTC, yinghj commented on Project/Assets/Editor/Twine Importer/TwineJsonParser.cs
> +        Regex invisibleTextRegex = new Regex("(\\[\\[([^\\]]*)\\]\\])|(\\(\\([^)]*\\)\\))");
Commenting the regex. Same as above.

2018-02-10 22:02 UTC, Charlieranderson approved these changes
Chelsea's changes have been implemented, looks good, we should merge asap

2018-02-10 22:13 UTC, tedward111 approved these changes

2018-02-10 22:14 UTC, merged